### PR TITLE
ILMerge assemblies into Zombify.Server.exe

### PR DESCRIPTION
**Pull request by jhollingworth**
The version of Newtonsoft.Json we use internally conflicts with your
version. To get around this we are ILMerging your version into the
assembly so we dont have any nasty pains

### CODE REVIEW

**Comment by robashton** [comment]
Works for me, I'll merge this on mon

Sent from my iPhone

On 22 Feb 2013, at 16:47, James Hollingworth notifications@github.com
wrote:

The version of Newtonsoft.Json we use internally conflicts with your
version. To get around this we are ILMerging your version into the

## assembly so we dont have any nasty pains

You can merge this Pull Request by running

  git pull https://github.com/jhollingworth/zombify master

Or view, comment on, or merge it at:

  https://github.com/robashton/zombify/pull/11
Commit Summary
- ILMerge assemblies into exe

File Changes
- _A_ NuGet/content/test/client.coffeehttps://github.com/robashton/zombify/pull/11/files#diff-0(21)
- _A_ NuGet/content/test/system.coffeehttps://github.com/robashton/zombify/pull/11/files#diff-1(18)
- _A_ build/ILMerge/Castle.Core.dllhttps://github.com/robashton/zombify/pull/11/files#diff-2(0)
- _A_ build/ILMerge/ILMerge
  License.rtfhttps://github.com/robashton/zombify/pull/11/files#diff-3(104)
- _A_ build/ILMerge/ILMerge.dochttps://github.com/robashton/zombify/pull/11/files#diff-4(0)
- _A_ build/ILMerge/ILMerge.exehttps://github.com/robashton/zombify/pull/11/files#diff-5(0)
- _A_ build/ILMerge/ILMerge.exe.confighttps://github.com/robashton/zombify/pull/11/files#diff-6(5)
- _A_ build/ILMerge/Moq.Silverlight.and.Castle.Core.dllhttps://github.com/robashton/zombify/pull/11/files#diff-7(0)
- _A_ build/ILMerge/Moq.Silverlight.dllhttps://github.com/robashton/zombify/pull/11/files#diff-8(0)
- _A_ build/ILMerge/foo.dllhttps://github.com/robashton/zombify/pull/11/files#diff-9(0)
- _M_ build/copy.msbuildhttps://github.com/robashton/zombify/pull/11/files#diff-10(3)
- _M_ src/Zombify.Server/Main.cshttps://github.com/robashton/zombify/pull/11/files#diff-11(4)
- _M_ src/Zombify.Server/Zombify.Server.csprojhttps://github.com/robashton/zombify/pull/11/files#diff-12(7)
- _M_ src/zombify/server/Zombify.Server.exehttps://github.com/robashton/zombify/pull/11/files#diff-13(0)

Patch Links:
- https://github.com/robashton/zombify/pull/11.patch
- https://github.com/robashton/zombify/pull/11.diff

**Comment by jhollingworth** [comment]
Any chance you could push a new version to NPM?

**Comment by robashton** [comment]
Ah yes, sorry - of course

**Comment by robashton** [comment]
Having a go at this now - I have to do a push to NuGet as well - wish me luck

**Comment by robashton** [comment]
Were you pulling it from NuGet or NPM? I notice that the built NPM package
still has all the DLLs in it - is that okay/intentional?

On Wed, Mar 6, 2013 at 4:55 PM, James Hollingworth <notifications@github.com

**Comment by robashton** [comment]
Or are they just there "because" and actually it's ILMerged perfectly fine
and the code has been updated to not copy the DLLs around?

**Comment by robashton** [comment]
Well, buggeit, I'm trusting you've done it all great and I'll test it later
- pushing up

I'll be using this in a couple of days so it had better work _shakes fist_

**Comment by jhollingworth** [comment]
We're using it via npm. It's probably that I forgot to delete the old
assemblies

On 6 Mar 2013, at 05:04 PM, robashton notifications@github.com wrote:

Or are they just there "because" and actually it's ILMerged perfectly fine
and the code has been updated to not copy the DLLs around?

On Wed, Mar 6, 2013 at 5:03 PM, Rob Ashton robashton@codeofrob.com wrote:

> Were you pulling it from NuGet or NPM? I notice that the built NPM
> package
> still has all the DLLs in it - is that okay/intentional?
> 
> On Wed, Mar 6, 2013 at 4:55 PM, James Hollingworth <
> notifications@github.com> wrote:
> 
> > <
> > https://a248.e.akamai.net/camo.github.com/fbc6a757de40ca6fddee803bff8828e5b3f795c3/687474703a2f2f7777772e70616b6b6f746f6973746f2e636f6d2f6174746163686d656e74732f796c65696e656e2d6b65736b757374656c752f383833333764313334393139383334332d6d696e757374612d74756c65652d692d732d61652d6a657375732d736179732d6d656d652d67656e657261746f722d676f6f642d6c75636b2d646f6e2d742d6b696c6c2d796f757273656c662d3562336165362e6a7067>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/robashton/zombify/pull/11#issuecomment-14511842>
> > .

—
Reply to this email directly or view it on
GitHubhttps://github.com/robashton/zombify/pull/11#issuecomment-14512549
.

**Comment by robashton** [comment]
Not a problem, I notice the code only copies across .exe so that's great

On Wed, Mar 6, 2013 at 5:06 PM, James Hollingworth <notifications@github.com

> wrote:
> 
> We're using it via npm. It's probably that I forgot to delete the old
> assemblies
>

**Comment by robashton** [comment]
I for one welcome our new IlMerged overlords

**Comment by jhollingworth** [comment]
Hmm, there seems to be some issues doing npm install zombify on windows

image

**Comment by robashton** [comment]
Sure that's a zombify problem?

(Btw, I packaged it on Windows, so this can't be a x-platform issue)

**Comment by jhollingworth** [comment]
fuck, sorry ignore me. I'd been messing with package.json

On 7 March 2013 13:00, robashton notifications@github.com wrote:

> Sure that's a zombify problem?
> 
> (Btw, I packaged it on Windows, so this can't be a x-platform issue)
> 
> On Thu, Mar 7, 2013 at 12:34 PM, James Hollingworth <
> notifications@github.com> wrote:
> 
> > Hmm, there seems to be some issues doing npm install zombify on windows
> > 
> > [image: image]<
> > https://f.cloud.github.com/assets/151172/232081/4c126c7e-8723-11e2-98b3-8291a3019e09.png>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/robashton/zombify/pull/11#issuecomment-14557540>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/robashton/zombify/pull/11#issuecomment-14559175
> .

## 

http://twitter.com/jhollingworth | http://github.com/jhollingworth |
http://linkedin.com/in/jhollingworth | +44 7866 843 864

**Comment by robashton** [comment]
:-)

On Thu, Mar 7, 2013 at 1:02 PM, James Hollingworth <notifications@github.com

> wrote:
> 
> fuck, sorry ignore me. I'd been messing with package.json
>

**Pull request merged**
