### PR TITLE
Add node-inspector / a tool to debug the java- & coffeescript files

### PR DESCRIPTION
**Pull request by ToJans**
Unfortunately there seems to be a problem; I am unable to continue
debugging from the browser; the process just hangs... I might look at this another time, but
ATM I lost to much time with this already.

Nevertheless I think this might be an interesting "Rube Goldberg"-like addition, hence the pull request...

### CODE REVIEW

**Comment by ToJans** [comment]
FYI you need to call zombify--debug-brk.bat (this might have gotten lost in the huge commit due to including the node-inspector package).

**Comment by robashton** [comment]
JEEEEEEES

**Comment by robashton** [comment]
this is something that'll need careful addition - I doubt we need all those files to make it work in the NuGet package!

**Comment by ToJans** [comment]
Maybe we can just install npm, and work our way up from there?

**Comment by ToJans** [comment]
Never mind... back to the drawing board; this looks hideous...

**Pull request closed without merging**
